# Clave única y nombre de tu proyecto
sonar.projectKey=cap-enterprise-monorepo
sonar.projectName=CAP Classroom Assignment Platform

# Directorios a escanear (Frontend y Backend)
sonar.sources=./backend, ./frontend

# Excluir carpetas que no queremos escanear como código fuente
sonar.exclusions=**/node_modules/**, **/.vite/**, **/venv/**, **/target/**, **/__test__/**

# Reporte de dependencias (SCA)
sonar.dependencyCheck.htmlReportPath=dependency-check-report.html

# 👇 LA LÍNEA MÁGICA QUE SOLUCIONA TU ERROR 👇
sonar.java.binaries=backend/schedule-service/target/classes