name: Dev - Build & Push to Docker Hub

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_KENNYCIS }}
          password: ${{ secrets.DOCKER_KENNYCISPASSWORD }}

      - name: Build and Push Auth Service
        run: |
          docker build -t ${{ secrets.DOCKER_KENNYCIS }}/cap-auth-service:dev ./backend/auth-service || docker build -t ${{ secrets.DOCKER_KENNYCIS }}/cap-auth-service:dev ./auth-service
          docker push ${{ secrets.DOCKER_KENNYCIS }}/cap-auth-service:dev

      - name: Build and Push Room Service
        run: |
          docker build -t ${{ secrets.DOCKER_KENNYCIS }}/cap-room-service:dev ./backend/room-service || docker build -t ${{ secrets.DOCKER_KENNYCIS }}/cap-room-service:dev ./room-service
          docker push ${{ secrets.DOCKER_KENNYCIS }}/cap-room-service:dev

      - name: Build and Push Reservation Service
        run: |
          docker build -t ${{ secrets.DOCKER_KENNYCIS }}/cap-reservation-service:dev ./backend/reservations-service || docker build -t ${{ secrets.DOCKER_KENNYCIS }}/cap-reservation-service:dev ./reservations-service
          docker push ${{ secrets.DOCKER_KENNYCIS }}/cap-reservation-service:dev

      - name: Build and Push Notification Service
        run: |
          docker build -t ${{ secrets.DOCKER_KENNYCIS }}/cap-notification-service:dev ./backend/notifications-service || docker build -t ${{ secrets.DOCKER_KENNYCIS }}/cap-notification-service:dev ./notifications-service
          docker push ${{ secrets.DOCKER_KENNYCIS }}/cap-notification-service:dev