name: PROD - Promote Images from QA

on:
  push:
    branches:
      - main

jobs:
  promote-to-prod:
    name: Promote QA Images to Production
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_KENNYCIS }}
          password: ${{ secrets.DOCKER_KENNYCISPASSWORD }}

      - name: Promote Auth Service
        run: |
          docker pull ${{ secrets.DOCKER_KENNYCIS }}/cap-auth-service:qa
          docker tag ${{ secrets.DOCKER_KENNYCIS }}/cap-auth-service:qa ${{ secrets.DOCKER_KENNYCIS }}/cap-auth-service:prod
          docker push ${{ secrets.DOCKER_KENNYCIS }}/cap-auth-service:prod

      - name: Promote Room Service
        run: |
          docker pull ${{ secrets.DOCKER_KENNYCIS }}/cap-room-service:qa
          docker tag ${{ secrets.DOCKER_KENNYCIS }}/cap-room-service:qa ${{ secrets.DOCKER_KENNYCIS }}/cap-room-service:prod
          docker push ${{ secrets.DOCKER_KENNYCIS }}/cap-room-service:prod

      - name: Promote Reservation Service
        run: |
          docker pull ${{ secrets.DOCKER_KENNYCIS }}/cap-reservation-service:qa
          docker tag ${{ secrets.DOCKER_KENNYCIS }}/cap-reservation-service:qa ${{ secrets.DOCKER_KENNYCIS }}/cap-reservation-service:prod
          docker push ${{ secrets.DOCKER_KENNYCIS }}/cap-reservation-service:prod

      - name: Promote Notification Service
        run: |
          docker pull ${{ secrets.DOCKER_KENNYCIS }}/cap-notification-service:qa
          docker tag ${{ secrets.DOCKER_KENNYCIS }}/cap-notification-service:qa ${{ secrets.DOCKER_KENNYCIS }}/cap-notification-service:prod
          docker push ${{ secrets.DOCKER_KENNYCIS }}/cap-notification-service:prod